# Generated by Django 5.2.1 on 2025-05-14 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunitat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comarca',
            fields=[
                ('nom', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('habitants', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Repte',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titol', models.CharField(max_length=75)),
                ('visiblitat', models.CharField(choices=[('ME', 'Només jo'), ('AMICS', 'Només amistats'), ('PUBLIC', 'Públic')], default='PUBLIC', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titol', models.CharField(max_length=75)),
                ('text', models.CharField(max_length=255)),
                ('icona', models.URLField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.flaticon.es%2Ficono-gratis%2Ftrofeo_536056&psig=AOvVaw1bTfl895dsISlq8UIpoJmT&ust=1747325495554000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCPDL0u2so40DFQAAAAAdAAAAABAE')),
            ],
        ),
        migrations.CreateModel(
            name='Original',
            fields=[
                ('repte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comunitat.repte')),
                ('permissos', models.TextField(choices=[('ME', 'Només jo'), ('AMICS', 'Només amistats'), ('PUBLIC', 'Públic')], default='PUBLIC')),
            ],
            bases=('comunitat.repte',),
        ),
        migrations.AddField(
            model_name='usuari',
            name='insignies',
            field=models.ManyToManyField(blank=True, to='comunitat.insignia'),
        ),
        migrations.CreateModel(
            name='Poblacio',
            fields=[
                ('nom', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('comarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poblacio_comarca', to='comunitat.comarca')),
            ],
        ),
        migrations.CreateModel(
            name='Amistat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('foto', models.URLField()),
                ('usuari1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistats_usuari1', to=settings.AUTH_USER_MODEL)),
                ('usuari2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistats_usuari2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuari1', 'usuari2'), name='amistat_unica')],
            },
        ),
        migrations.CreateModel(
            name='Copiat',
            fields=[
                ('repte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comunitat.repte')),
                ('basat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunitat.original')),
            ],
            bases=('comunitat.repte',),
        ),
        migrations.CreateModel(
            name='Distancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.FloatField()),
                ('comarca1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distancia_comarca1', to='comunitat.comarca')),
                ('comarca2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distancia_comarca2', to='comunitat.comarca')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('comarca1', 'comarca2'), name='distancia_unic')],
            },
        ),
        migrations.CreateModel(
            name='Missatge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField()),
                ('text', models.TextField()),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missatge_emisor', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missatge_receptor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('emisor', 'receptor', 'dataHora'), name='missatge_unic')],
            },
        ),
    ]
