# Generated by Django 5.2.1 on 2025-05-14 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunitat', '0002_comarca_repte_insignia_original_usuari_insignies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repte',
            name='usuari',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='repte_usuari', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amistat',
            name='usuari1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='amistats_usuari1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='amistat',
            name='usuari2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='amistats_usuari2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='copiat',
            name='basat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='comunitat.original'),
        ),
        migrations.AlterField(
            model_name='distancia',
            name='comarca1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='distancia_comarca1', to='comunitat.comarca'),
        ),
        migrations.AlterField(
            model_name='distancia',
            name='comarca2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='distancia_comarca2', to='comunitat.comarca'),
        ),
        migrations.AlterField(
            model_name='missatge',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='missatge_emisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='missatge',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='missatge_receptor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poblacio',
            name='comarca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pertany', to='comunitat.comarca'),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='insignies',
            field=models.ManyToManyField(blank=True, related_name='obte', to='comunitat.insignia'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcio', models.CharField(max_length=255)),
                ('foto', models.URLField()),
                ('likes', models.ManyToManyField(blank=True, to='comunitat.perfil')),
                ('repte', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='preferit', to='comunitat.repte')),
                ('usuari', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='creat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assolit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.URLField()),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('comarca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='comunitat.comarca')),
                ('repte', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='comunitat.repte')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('repte', 'comarca'), name='assolit_unic')],
            },
        ),
        migrations.CreateModel(
            name='Descripcio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcio', models.TextField()),
                ('comarca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='descripcio_comarca', to='comunitat.comarca')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='descripcio_original', to='comunitat.original')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('original', 'comarca'), name='descripcio_unic')],
            },
        ),
    ]
