# Generated by Django 5.2.1 on 2025-05-14 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('comunitat', '0003_repte_usuari_alter_amistat_usuari1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuari',
            options={},
        ),
        migrations.AddField(
            model_name='usuari',
            name='poblacio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='pertany', to='comunitat.poblacio'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='usuari',
            constraint=models.UniqueConstraint(fields=('username',), name='usuari_unic'),
        ),
    ]
