# Generated by Django 5.2.1 on 2025-06-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunitat', '0004_alter_usuari_options_usuari_poblacio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amistat',
            name='foto',
            field=models.ImageField(upload_to='amistats/'),
        ),
    ]
