# Generated by Django 5.2.1 on 2025-06-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunitat', '0006_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assolit',
            name='foto',
            field=models.ImageField(upload_to='reptes/'),
        ),
    ]
